# Generated by Django 2.2.13 on 2022-03-07 13:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehandler',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.file_path),
        ),
    ]
